[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb==1.0.10",
    "faiss-cpu==1.11.0",
    "langchain==0.3.25",
    "langchain-community==0.3.24",
    "langchain-core==0.3.59",
    "langchain-groq==0.3.2",
    "numpy>=2.1.0",
    "pydantic==2.11.4",
    "pymupdf==1.26.0",
    "pypdf==5.5.0",
    "python-dotenv==1.1.0",
    "sentence-transformers==4.1.0",
]
